### ISSUE TITLE
brotli compressed build fails to run in firefox

### ISSUE THREAD

**Issue by Tripl3Design** [JohannesDeml/UnityWebGL-LoadingTest#4] opened 2022-09-08 08:50 UTC
When I try to build with brotli compression and no fallback (Unity 2021.3.8f1), firefoxs failed to build the game.
I think it's an (old) general Unity bug.
Don't you have the same experience?

[demo with brotli compression](https://furnitise.nl/webXR/)
[issuetracker](https://issuetracker.unity3d.com/issues/brotli-compressed-build-fails-to-run-in-firefox)

**Comment by JohannesDeml** [comment] 2022-09-08 10:45
For me local builds don't run in firefox, but normal builds deployed to the server don't have that kind of problem. You can have a look at the live builds here: https://github.com/JohannesDeml/UnityWebGL-LoadingTest#live-demos
They are built from this repo, so you should be able to reproduce them.

**Comment by Tripl3Design** [comment] 2022-09-09 07:41
Thanks for the response.
So strange. If I try the build from the repo: (2021.3.6f1-webgl2) it works in firefox, but my build is broken.

[webGL loadingTest](https://furnitise.nl/loadingTest/)
Color Space: linear;
Graphics APIs: WebGL 2 only
Static Batching: on

**Comment by JohannesDeml** [comment] 2022-09-09 12:15
My guess would be, that your server configuration then has some problems handling the brotli files.
To verify that it has nothing to do with your unity build, you can also download the files deployed on my server from there release section: https://github.com/JohannesDeml/UnityWebGL-LoadingTest/releases
If you deploy that to your server, and it still does not work, then you can be sure, that your server config is the problem.

**Comment by JohannesDeml** [comment] 2022-11-11 06:58
Closing this for now, since it does not seem to be linked to this project and is more of a general server configuration problem

**Closed by JohannesDeml** 2022-11-11 06:58 UTC
